name: CI/CD Pipeline with Enhanced Security Scanning

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      # Frontend Security Scanning
      - name: Install Frontend dependencies
        run: npm install

      - name: Run Snyk to check frontend dependencies
        uses: snyk/actions/node@v1
        with:
          args: test

      # Backend Security Scanning
      - name: Install Backend dependencies
        run: pip install -r requirements.txt

      - name: Python Dependency Analysis with Safety
        run: safety check -r requirements.txt

      - name: Static Code Analysis with Bandit
        run: bandit -r .

      # Build and Scan Backend Docker Image
      - name: Build Docker image for Petstore backend
        run: docker build -t petstore-backend .

      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: petstore-backend

      # OWASP ZAP Scan
      - name: Start Petstore Backend
        run: docker run -d -p 8080:8080 petstore-backend

      - name: Run OWASP ZAP Active Scan
        uses: zaproxy/action-full-scan@v0.3.0
        with:
          target: 'http://localhost:8080'

      # Secrets Scanning
      - name: Run Gitleaks Secret Scan
        uses: zricethezav/gitleaks-action@v1.1.3
        with:
          args: --path=. --report=gitleaks-report.json

      # Upload Scan Reports as Artifacts
      - name: Upload Bandit report
        uses: actions/upload-artifact@v2
        with:
          name: bandit-report
          path: bandit-report.json

      - name: Upload Safety report
        uses: actions/upload-artifact@v2
        with:
          name: safety-report
          path: safety-report.json

      - name: Upload Trivy report
        uses: actions/upload-artifact@v2
        with:
          name: trivy-report
          path: trivy-report.json

  notify:
    needs: security_scan
    runs-on: ubuntu-latest
    steps:
      - name: Notify Slack on Failure
        if: failure()
        uses: slackapi/slack-github-action@v1.23.0
        with:
          channel-id: ${{ C081RFYNM96 }}
          text: |
            🚨 Security scan failed in the CI/CD pipeline! 🚨
            Please check the attached reports for more details.
        env:
          SLACK_WEBHOOK_URL: ${{ https://hooks.slack.com/services/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 }}
