name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up Node.js (for frontend)
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install frontend dependencies
        run: npm install
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: 'javascript, python'
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
      - name: Run Snyk to check dependencies
        uses: snyk/actions/node@v1
        with:
          args: test
      - name: Docker Build
        run: docker build -t myapp .
      - name: Scan Docker Image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: myapp
      - name: Run OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.3.0
        with:
          target: 'http://localhost:8000'
